name: "PR Merge on time"

on:
  schedule:
  - cron: '00 13 * * *'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge:
    name: "Auto Merge on time"
    runs-on: "ubuntu-latest"
    
    steps:
      - name: "Merge pull request"
        uses: "actions/github-script@v3"
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const query = `query($owner:String!, $name:String!) {
              repository(owner: $owner, name: $name) {
                pullRequests(last: 100, states: OPEN) {
                  edges {
                    node {
                      number
                      headRefName
                      author {
                        login
                      }
                      repository {
                        name
                      }
                    }
                  }
                }
              }
            }`
            
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
            }
            console.log(context.repo);
